/*
 * Copyright (c) 2026 Samir Das <samiruor@gmail.com>. All rights reserved.
 *
 * PROPRIETARY AND CONFIDENTIAL.
 * Unauthorized copying, reproduction, distribution, or modification of this
 * file, via any medium, is strictly prohibited.
 * All rights reserved.
 */

/* Autogenerated file, don't edit */
#ifndef BIOS_OFFSETS_H
#define BIOS_OFFSETS_H

#define BIOS_ENTRY_SIZE(name) (name##_end - name)

#define BIOS_OFFSET__bios_int10 0x00000040
#define BIOS_OFFSET__bios_int10_end 0x0000007f
#define BIOS_OFFSET__bios_int15 0x00000080
#define BIOS_OFFSET__bios_int15_end 0x000000b8
#define BIOS_OFFSET__bios_intfake 0x00000030
#define BIOS_OFFSET__bios_intfake_end 0x00000038
#define BIOS_OFFSET____CALLER_CLOBBER 0x000000c0
#define BIOS_OFFSET____CALLER_SP 0x000000bc
#define BIOS_OFFSET____CALLER_SS 0x000000b8
#define BIOS_OFFSET__e820_query_map 0x000000c4
#define BIOS_OFFSET__int10_handler 0x0000016c
#define BIOS_OFFSET__int15_handler 0x00000298
#define BIOS_OFFSET____locals 0x000000b8
#define BIOS_OFFSET____locals_end 0x000000c4
#define BIOS_OFFSET__memcpy16 0x00000000

#endif
